theme: jekyll-theme-dinky

# Added information below. 
title: "Sophie Engle"
description: "Example Github Pages website for CS 186-02 Community Engaged CS."

# Enables using emoji. See: https://help.github.com/en/articles/emoji-on-github-pages
plugins:
  - jemoji
